# Generated by Django 4.2.5 on 2023-09-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carousels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="carousels/%y/%m/")),
                ("title", models.CharField(max_length=150)),
                ("sub_title", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
