# Generated by Django 4.2.5 on 2023-09-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carousels",
            options={"verbose_name": "Carousel", "verbose_name_plural": "Carousels"},
        ),
        migrations.AddField(
            model_name="carousels",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Order in which the carousel appears"
            ),
        ),
    ]
