# Generated by Django 4.2.5 on 2023-09-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_carousels_options_carousels_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="carousels",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
