# Generated by Django 4.2.5 on 2023-09-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.IntegerField(default=0),
        ),
    ]
