# Generated by Django 4.2.5 on 2023-10-02 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0006_auto_20231002_1309"),
    ]

    operations = []
