# Generated by Django 4.2.5 on 2023-10-18 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0012_address_profile_address"),
    ]

    operations = []
