# Generated by Django 4.2.5 on 2023-10-18 10:00

from django.db import migrations


def create_empty_addresses(apps, schema_editor):
    User1 = apps.get_model('custom_user', 'User')
    Address1 = apps.get_model('custom_user', 'Address')  # Replace with your app's name

    for user in User1.objects.all():
        # Create an Address object for each user with empty fields
        Address1.objects.create(
            user=user,
            address_name='',  # Set all fields to empty values
            recipient_name='',
            street_address1='',
            street_address2='',
            city='',
            postal_code=0,  # Set to 0 for integer fields
            country='',
            state='',
        )

class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0014_alter_address_address_name_and_more"),
    ]

    operations = []
