# Generated by Django 4.2.5 on 2023-10-18 10:19

from django.db import migrations


def add_foreign_keys_to_address(apps, schema_editor):
    User = apps.get_model('custom_user', 'User')
    Address = apps.get_model('custom_user', 'Address')

    for user in User.objects.all():
        # Determine the appropriate Address record for the user, e.g., by some criteria
        # For this example, we assume a one-to-one mapping between User and Address
        address = Address.objects.filter(user=None).first()

        # Update the User record with the address
        user.address = address
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0016_auto_20231018_1305"),
    ]

    operations = [
        migrations.RunPython(add_foreign_keys_to_address)
    ]
