# Generated by Django 4.2.5 on 2023-10-18 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0018_alter_address_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="address_name",
        ),
        migrations.RemoveField(
            model_name="address",
            name="city",
        ),
        migrations.RemoveField(
            model_name="address",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="address",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="address",
            name="recipient_name",
        ),
        migrations.RemoveField(
            model_name="address",
            name="street_address1",
        ),
        migrations.RemoveField(
            model_name="address",
            name="street_address2",
        ),
        migrations.RemoveField(
            model_name="address",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="address",
            name="user",
        ),
    ]
