# Generated by Django 4.2.5 on 2023-10-18 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "custom_user",
            "0019_remove_address_address_name_remove_address_city_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
