# Generated by Django 4.2.5 on 2023-09-12 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_delete_products"),
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
