# Generated by Django 4.2.5 on 2023-09-19 16:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, populate_from="name"),
        ),
    ]
