# Generated by Django 4.2.5 on 2023-11-08 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_created_at_order_status_order_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
