# Generated by Django 4.2.5 on 2023-11-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Complete", "Complete"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
