# Generated by Django 4.2.5 on 2023-09-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(null=True, upload_to="products/"),
        ),
    ]
