# Generated by Django 4.2.5 on 2023-11-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_created_at_order_status_order_updated_at_and_more"),
        ("products", "0008_alter_cart_options_alter_cartitems_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
        ),
    ]
